# Generated by Django 3.2.9 on 2022-03-04 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresses',
            name='if_c_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.counsellordetail'),
        ),
        migrations.AlterField(
            model_name='adresses',
            name='if_p_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.pharmacistdetail'),
        ),
    ]
