# Generated by Django 3.2.9 on 2022-02-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adresses',
            old_name='Tole',
            new_name='tole',
        ),
    ]
