# Generated by Django 3.2.9 on 2022-02-21 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
    ]
