# Generated by Django 3.2.9 on 2022-06-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('age', models.PositiveIntegerField()),
                ('prescription', models.FileField(upload_to='prescription_img/')),
                ('prescripted_by', models.CharField(max_length=35)),
                ('prescripted_for', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
