# Generated by Django 3.2.9 on 2022-06-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadprescription',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
