# Generated by Django 3.2.9 on 2022-03-04 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='photos/product_images')),
                ('cost', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('dose_child', models.CharField(max_length=200)),
                ('dose_adult', models.CharField(max_length=200)),
                ('contraindiction', models.CharField(max_length=500)),
                ('indiction', models.CharField(max_length=500)),
                ('special_precautions', models.CharField(max_length=500)),
                ('adverse_effect', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.category')),
                ('pharmacy_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.pharmacistdetail')),
            ],
        ),
    ]
