# Generated by Django 3.2.9 on 2022-04-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacistdetail',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
