# Generated by Django 3.2.9 on 2022-03-03 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacistdetail',
            name='profile_image',
            field=models.ImageField(upload_to='profile/pharmacist_profile_image'),
        ),
        migrations.AlterField(
            model_name='pharmacistdetail',
            name='registered_doc',
            field=models.FileField(upload_to='doc/pharmacist_registred_document'),
        ),
        migrations.CreateModel(
            name='CounsellorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counsellor_name', models.CharField(max_length=100, unique=True)),
                ('profile_image', models.ImageField(upload_to='profile/counsellor_profile_image')),
                ('counsellor_email', models.EmailField(max_length=100, unique=True)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
                ('registration_no', models.CharField(max_length=15, unique=True)),
                ('registered_doc', models.FileField(upload_to='doc/counsellor_registred_document')),
                ('work_start', models.CharField(max_length=2)),
                ('work_end', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
