# Generated by Django 3.2.9 on 2022-02-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='licence_no',
        ),
        migrations.RemoveField(
            model_name='account',
            name='registration_no',
        ),
    ]
