# Generated by Django 3.2.9 on 2022-02-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220224_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type_user',
            old_name='is_admin',
            new_name='is_administrator',
        ),
    ]
