# Generated by Django 3.2.9 on 2022-02-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
