# Generated by Django 3.2.9 on 2022-02-08 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type_user',
            name='id',
        ),
        migrations.AlterField(
            model_name='type_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
