# Generated by Django 3.2.9 on 2022-02-09 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220208_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacistDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField(unique=True)),
                ('ogrn_number', models.IntegerField(unique=True)),
                ('inn_number', models.IntegerField(unique=True)),
                ('licence', models.FileField(upload_to='pharmacy_licence/pharmacist_licence')),
                ('pharmacy_name', models.CharField(max_length=100, unique=True)),
                ('telephone', models.IntegerField(unique=True)),
                ('pharmacy_email', models.EmailField(max_length=100, unique=True)),
                ('estd_date', models.DateTimeField()),
                ('registered_doc', models.FileField(upload_to='pharmacy_doc/pharmacist_registred_document')),
                ('profile_image', models.ImageField(upload_to='photos/pharmacist_profile_image')),
                ('working_days', models.CharField(max_length=200)),
                ('working_hours_start', models.TimeField()),
                ('working_hour_end', models.TimeField()),
                ('description', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
