# Generated by Django 3.2.9 on 2022-05-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
