# Generated by Django 3.2.9 on 2022-06-07 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='counsellor_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counsellor_details', to='account.counsellordetail'),
        ),
    ]
