# Generated by Django 3.2.9 on 2022-05-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220503_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(max_length=150),
        ),
    ]
