# Generated by Django 3.2.9 on 2022-06-06 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('orders', '0008_alter_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='pharmacy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.pharmacistdetail'),
            preserve_default=False,
        ),
    ]
